# Generated by Django 5.0.6 on 2025-02-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0015_group_home_group_icon'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='url')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='MenuGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='url')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sistema/profile_images')),
                ('tipoUsuario', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=20, null=True, verbose_name='Tipo Usuario')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.area', verbose_name='Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
