# Generated by Django 5.0.6 on 2025-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayuda',
            name='icon',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Icono'),
        ),
    ]
