# Generated by Django 5.0.6 on 2025-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_ayuda_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menugrupo',
            name='icon',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Icono'),
        ),
    ]
