# Generated by Django 4.2.8 on 2025-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tema_ayuda_detalle',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
