# Generated by Django 4.2.8 on 2025-02-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('ticket', '0002_ticket_tema_ayuda_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_area', to='general.area'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.estadoticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
