# Generated by Django 4.2.8 on 2025-02-06 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_alter_ticket_area_alter_ticket_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='usuario_solicitante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
