# Generated by Django 4.2.8 on 2025-02-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_usuario_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nivel_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.nivelservicio'),
        ),
    ]
