# Generated by Django 4.2.8 on 2025-02-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_usuario_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usuario_solicitante_temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario_fuente',
            field=models.CharField(choices=[('email', 'Email'), ('telefono', 'Teléfono'), ('sistema', 'Sistema Interno')], default='sistema', max_length=100),
        ),
    ]
