# Generated by Django 4.2.8 on 2025-02-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_usuario_solicitante_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accionAplicada',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='causaRaiz',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
