# Generated by Django 4.2.8 on 2025-02-07 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_ticket_accionaplicada_ticket_causaraiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('estado_anterior', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_estado_anterior', to='ticket.estadoticket')),
                ('estado_nuevo', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_estado_nuevo', to='ticket.estadoticket')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ticket.ticket')),
            ],
        ),
    ]
