# Generated by Django 4.2.8 on 2025-02-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_ticketmovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickeTrasferir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('operador_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadorAnterio', to=settings.AUTH_USER_MODEL)),
                ('operador_nuevo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadorNuevo', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketTrasferir', to='ticket.ticket')),
            ],
        ),
    ]
