# Generated by Django 4.2.8 on 2025-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_rename_ticketrasferir_ticketransferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoticket',
            name='color',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
