# Generated by Django 4.2.8 on 2025-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_estadoticket_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoticket',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
