# Generated by Django 4.2.8 on 2025-02-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_estadoticket_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoticket',
            name='color',
        ),
    ]
