# Generated by Django 4.2.8 on 2025-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_estadoticket_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoticket',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
