# Generated by Django 4.2.8 on 2025-02-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_estadoticket_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoticket',
            name='dataLucide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
