# Generated by Django 4.2.8 on 2025-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_estadoticket_datalucide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoticket',
            name='dataLucide',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
